### ISSUE TITLE
Installation (HACS) - not a valid repository

### ISSUE THREAD

**Issue by phaze75** [dreautall/ha-stromnetzgraz#11]
Hi,

I just tried your [Installation (HACS)](https://github.com/dreautall/ha-stromnetzgraz#installation-hacs) procedure. Unfortunately, Home Assistant keeps telling me, that it is not a valid repository:

![image](https://github.com/dreautall/ha-stromnetzgraz/assets/2933023/99fe2abd-fc76-425a-a46b-8114c1e3751c)

The [Home Assistant Wiki](https://developers.home-assistant.io/docs/add-ons/repository/#:~:text=A%20user%20can%20add%20a,textarea%20and%20click%20on%20Save.
) tells me that "Each repository is required to contain repository.yaml at the root in the git repository." However, I can't see a "repository.yaml" in your repository.

What am I missing?

**Comment by dreautall** [comment]
Hey! It's not an add-on, it's just a custom integration in HACS. Please see here for more detail about HACS: https://hacs.xyz/

Alternatively, you can install it manually.

**Comment by phaze75** [comment]
Hey! Thanks for your hint. That worked. My bad. Sorry!
