### ISSUE TITLE
Webportal broken/down?

### ISSUE THREAD

**Issue by wieluk** [dreautall/ha-stromnetzgraz#13]
Is it just for me or is the Stromnetz Graz Webportal down?

**Comment by werners7** [comment]
The same for me!

**Comment by sebinity** [comment]
Seems to be a general problem at the moment:

![Screenshot_20240114-185722](https://github.com/dreautall/ha-stromnetzgraz/assets/75244862/a24dfa80-fdcd-4476-9c7e-897e7763d3da)

**Comment by wieluk** [comment]
Seems back up.
