### ISSUE TITLE
Deprecated Constant 'ENERGY_KILO_WATT_HOUR'

### ISSUE THREAD

**Issue by danilichti** [dreautall/ha-stromnetzgraz#14]
ENERGY_KILO_WATT_HOUR was used from stromnetzgraz, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead

![CleanShot 2024-03-02 at 08 13 58](https://github.com/dreautall/ha-stromnetzgraz/assets/73495201/0353735d-1196-42ae-b91d-fea16b0c9bee)

**Comment by dreautall** [comment]
thank you for the report!
