### ISSUE TITLE
Do not find the entity stromnetzgraz: consumption 

### ISSUE THREAD

**Issue by haudi31** [dreautall/ha-stromnetzgraz#19]
I find both sensor:meter_ entities but not the one I would need to display the usage. I readded the integration but always only find "1 device" with 2 entities.

**Comment by dreautall** [comment]
Hi, which meter do you really want, the meter reading or the meter consumption one? The meter consumption one is.. not good. I can't backfill the data properly, so it looks like this:
![image](https://github.com/dreautall/ha-stromnetzgraz/assets/109872040/04212fc2-d7d9-4231-bea0-d2b934139f11)


Do you have IME (15min) mode? It might take up to two days for it to be properly filled.

**Comment by haudi31** [comment]
Thanks for the answer. Would like to see my 15-min consumption. I have my ime installed for months. 

I thought we should not use the meter enterties?

**Comment by dreautall** [comment]
Yes exactly. Sorry maybe a misunderstanding on my site initially.

The `stromnetzgraz:energy_consumption:...` sensors are "external statistics", which means they won't show up basically anywhere except the energy dashboard. It looks like you also can't query them via templates, at least not via `states`. No idea how you can fetch them short of querying the database directly :(

Might be a question better suited for the Home Assistant forums. There are a couple of other energy integrations using external statistics as well, but I haven't found anyone trying to make an own graph or something like that.
